/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    month?: string;
                    /** @description Device IANA timezone for the upcoming 30-day window; defaults to UTC. */
                    timezone?: string;
                    /** @description preview returns at most 200 recent entries for attachment context; all totals still include every entry. Use /entries for the paginated activity feed. */
                    entries?: "all" | "preview";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Snapshot"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Backup"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description version=0 creates with a client UUID. Existing records require the current version. Identical create retries are idempotent. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /** Remove an account from Haven; retain transfer history and exclude future sync */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        version: number;
                    };
                };
            };
            responses: {
                /** @description Account removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            removed: boolean;
                        };
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description version=0 creates with a client UUID. Existing records require the current version. Identical create retries are idempotent. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Entry"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description version=0 creates with a client UUID. Existing records require the current version. Identical create retries are idempotent. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BankingStatus"];
                    };
                };
                /** @description Success */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            banks: components["schemas"]["TestBank"][];
                        };
                    };
                };
                /** @description Success */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        country: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            url: string;
                        };
                    };
                };
                /** @description Success */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Provider browser redirect. Requires an unexpired, single-use state bound to the HttpOnly authorization cookie. Codes and session IDs are never returned to JavaScript. */
        get: {
            parameters: {
                query: {
                    state: string;
                    code?: string;
                    error?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Return to Money with a sanitized connection outcome */
                303: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Success */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/connections/{id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BankingStatus"];
                    };
                };
                /** @description Success */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/connections/{id}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BankingStatus"];
                    };
                };
                /** @description Success */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create, rename, or hide a transaction category */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                /** @description Invalid fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Version or name conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banking/transactions/{id}/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update personal annotations without changing bank facts */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BankAnnotations"];
                };
            };
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BankAnnotations"];
                    };
                };
                /** @description Invalid fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Version or name conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Six-week month calendar including recurring previews and completed occurrences */
        get: {
            parameters: {
                query: {
                    month: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Calendar */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskCalendar"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantStatus"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssistantSettings"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantSettings"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssistantProviderUpdate"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantProvider"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssistantProviderRevision"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantStatus"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/provider/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssistantProviderRevision"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantStatus"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssistantChatRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantChatReply"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Persistent transaction review inbox */
        get: {
            parameters: {
                query?: {
                    view?: "review" | "history";
                    /** @description Opaque next_cursor from the previous page, scoped to the selected view. */
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Inbox and processing counts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewInbox"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/inbox/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss a suggestion */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Action completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: boolean;
                        };
                    };
                };
                /** @description Transaction or suggestion changed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/inbox/{id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save reviewed annotations atomically */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        category_id: string;
                        tags: string[];
                        notes: string;
                        version: number;
                        payment_units?: number;
                    };
                };
            };
            responses: {
                /** @description Action completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: boolean;
                        };
                    };
                };
                /** @description Transaction or suggestion changed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/inbox/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry failed reviews */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Action completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: boolean;
                        };
                    };
                };
                /** @description Transaction or suggestion changed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/inbox/{id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo automatic category and tags if the transaction has not been edited */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Action completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: boolean;
                        };
                    };
                };
                /** @description Transaction or suggestion changed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/inbox/{id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer a purchase clarification for background review */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        answer: string;
                    };
                };
            };
            responses: {
                /** @description Action completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: boolean;
                        };
                    };
                };
                /** @description Transaction or suggestion changed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List transactions with cursor pagination
         * @description 50 canonical transactions per page, ordered by date descending and ID ascending. Filters precede pagination. Balances and monthly totals come from /state independently.
         */
        get: {
            parameters: {
                query?: {
                    month?: string;
                    account?: string;
                    category?: string;
                    tag?: string;
                    search?: string;
                    payment?: string;
                    unlinked?: string;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A transaction page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityPage"];
                    };
                };
                /** @description Invalid filter or cursor */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/icons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brand icon for a payee or plan name, matched against the embedded Simple Icons catalogue (CC0); no outside service is contacted */
        get: {
            parameters: {
                query: {
                    name: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matched brand icon (24×24 single-path SVG artwork) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BrandIcon"];
                    };
                };
                /** @description No brand matches this name */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logo of a bank-synced account's bank, downloaded once from the address Enable Banking lists and then served from Haven's cache */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logo image */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/*": string;
                    };
                };
                /** @description Not a bank account, or the bank has no logo */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/followups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Recent follow-up activity for the Inbox, newest first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FollowUpEvents"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/followups/{id}/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Acknowledge a notice. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/followups/{id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Restore the task as it was before the assistant's latest change. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/followups/{id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Answer the assistant's question; it looks at the task again. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        answer: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            currency: "EUR";
            /** @description Exact EUR cents, serialized as a decimal string. */
            opening_minor: string;
            version: number;
            /**
             * @description Bank records are read-only and clearly marked as sandbox data; omitted for manual records.
             * @enum {string}
             */
            source?: "" | "enable_banking_sandbox";
            /** @description Latest bank-reported booked EUR balance in cents. Authoritative for bank accounts; transaction history must not be added again. */
            bank_balance_minor?: string;
        };
        Entry: {
            id: string;
            account_id: string;
            destination_id: string;
            /** @enum {string} */
            kind: "income" | "expense" | "transfer";
            /** @description Exact EUR cents, serialized as a decimal string. */
            amount_minor: string;
            date: string;
            payee: string;
            category: string;
            notes: string;
            deleted: boolean;
            version: number;
            /**
             * @description Bank amounts and payees are managed by sync; use the annotations endpoint for category, tags, and notes.
             * @enum {string}
             */
            source?: "" | "enable_banking_sandbox";
            /** @description Category ID; empty or omitted means Uncategorized. */
            category_id?: string;
            tags?: string[];
            /** @description Original bank description, separate from personal notes. */
            readonly bank_description?: string;
            /** @description Optional linked recurring payment. Saves the schedule and transaction annotations atomically; omitted preserves any existing schedule. */
            payment?: components["schemas"]["Task"];
            payment_units?: number;
        };
        Task: {
            id: string;
            title: string;
            date: string;
            time: string;
            timezone: string;
            /** @enum {string} */
            repeat: "none" | "daily" | "weekly" | "monthly" | "yearly";
            anchor_day: number;
            /** @enum {string} */
            kind: "task" | "appointment" | "payment";
            /** @description Exact EUR cents, serialized as a decimal string. */
            amount_minor: string;
            notes: string;
            done: boolean;
            deleted: boolean;
            version: number;
            /** @description Optional lower bound in EUR cents. Both bounds are null for unknown cost. */
            estimated_min_minor?: string | null;
            /** @description Optional upper bound in EUR cents, at least the lower bound. */
            estimated_max_minor?: string | null;
            plan?: components["schemas"]["PaymentPlan"];
            /** @description Missed occurrences lapse instead of staying overdue. Requires a repeat schedule. */
            routine?: boolean;
            /** @description The task this one continues, when the follow-up assistant replaced it. */
            readonly continues_from?: string;
            follow_up?: components["schemas"]["FollowUp"];
        };
        CompleteRequest: {
            id: string;
            version: number;
        };
        Error: {
            error: string;
        };
        Snapshot: {
            accounts: components["schemas"]["Account"][];
            entries: components["schemas"]["Entry"][];
            tasks: components["schemas"]["Task"][];
            balances: {
                [key: string]: string;
            };
            /** @description Exact EUR cents, serialized as a decimal string. */
            total_minor: string;
            /** @description Exact EUR cents, serialized as a decimal string. */
            income_minor: string;
            /** @description Exact EUR cents, serialized as a decimal string. */
            spending_minor: string;
            month: string;
            categories: components["schemas"]["Category"][];
            tags: string[];
            upcoming?: components["schemas"]["UpcomingCosts"];
        };
        Completion: {
            id: string;
            task_id: string;
            due_date: string;
            completed_at: string;
        };
        Backup: {
            /** @enum {string} */
            format: "haven-1";
            exported_at: string;
            accounts: components["schemas"]["Account"][];
            entries: components["schemas"]["Entry"][];
            tasks: components["schemas"]["Task"][];
            completions: components["schemas"]["Completion"][];
            categories: components["schemas"]["Category"][];
            tags: string[];
            assistant_settings: components["schemas"]["AssistantSettings"];
        };
        TestBank: {
            name: string;
            country: string;
            maximum_consent_validity: number;
            psu_types: string[];
        };
        BankAmount: {
            amount: string;
            currency: string;
        };
        BankBalance: {
            name: string;
            balance_amount: components["schemas"]["BankAmount"];
            balance_type: string;
            reference_date?: string;
        };
        BankTransaction: {
            entry_reference?: string;
            transaction_amount: components["schemas"]["BankAmount"];
            credit_debit_indicator: string;
            status: string;
            booking_date?: string;
            value_date?: string;
            creditor: {
                name: string;
            };
            debtor: {
                name: string;
            };
            remittance_information?: string[];
            creditor_account?: {
                iban?: string;
            };
            debtor_account?: {
                iban?: string;
            };
        };
        BankAccount: {
            identification_hash: string;
            name: string;
            details: string;
            currency: string;
            account_id: {
                iban: string;
            };
        };
        BankAccountData: {
            account: components["schemas"]["BankAccount"];
            balances: components["schemas"]["BankBalance"][];
            transactions: components["schemas"]["BankTransaction"][];
        };
        BankConnection: {
            /** Format: uuid */
            id: string;
            bank: string;
            country: string;
            /** @enum {string} */
            environment: "SANDBOX";
            /** @enum {string} */
            status: "connected" | "expired" | "disconnected";
            /** Format: date-time */
            valid_until: string;
            /** Format: date-time */
            synced_at: string | null;
            accounts: components["schemas"]["BankAccountData"][];
        };
        BankingStatus: {
            configured: boolean;
            /** @enum {string} */
            environment: "SANDBOX";
            connections: components["schemas"]["BankConnection"][];
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            hidden: boolean;
            version: number;
        };
        BankAnnotations: {
            category_id: string;
            tags: string[];
            notes: string;
            version: number;
            /** @description Optional linked recurring payment. Saves the schedule and transaction annotations atomically; omitted preserves any existing schedule. */
            payment?: components["schemas"]["Task"];
            payment_units?: number;
        };
        TaskOccurrence: {
            task: components["schemas"]["Task"];
            date: string;
            projected: boolean;
            completed: boolean;
        };
        TaskCalendar: {
            month: string;
            from: string;
            to: string;
            items: components["schemas"]["TaskOccurrence"][];
        };
        AssistantSettings: {
            /** @enum {string} */
            mode: "manual" | "on_request" | "proactive";
            /** @enum {string} */
            presentation: "button" | "card";
            offer_estimated_costs: boolean;
            skills: {
                "review-transaction": boolean;
                "plan-task": boolean;
                "organize-money": boolean;
                "follow-up": boolean;
            };
            version: number;
        };
        AssistantSkill: {
            id: string;
            name: string;
            description: string;
            supports_background: boolean;
        };
        AssistantStatus: {
            settings: components["schemas"]["AssistantSettings"];
            skills: components["schemas"]["AssistantSkill"][];
            model_connected: boolean;
            provider: components["schemas"]["AssistantProvider"];
        };
        AssistantProvider: {
            base_url: string;
            model: string;
            /** @enum {string} */
            protocol: "chat_completions" | "responses";
            has_api_key: boolean;
            version: number;
            tested_at: string | null;
        };
        AssistantProviderUpdate: {
            base_url: string;
            model: string;
            /** @enum {string} */
            protocol: "chat_completions" | "responses";
            version: number;
            api_key?: string | null;
        };
        AssistantChatRequest: {
            messages: {
                /** @enum {string} */
                role: "user" | "assistant";
                content: string;
            }[];
            timezone: string;
            entry_ids: string[];
            /** @description Recent editable conversation drafts; saved task revisions are checked against current records. */
            task_drafts?: components["schemas"]["Task"][];
        };
        AssistantChatReply: {
            message: string;
            task: components["schemas"]["Task"] | null;
            entries: components["schemas"]["Entry"][];
            /** @enum {string} */
            presentation: "button" | "card";
            reasons?: {
                [key: string]: string;
            };
        };
        AssistantProviderRevision: {
            version: number;
        };
        UpcomingCost: {
            task: components["schemas"]["Task"];
            /** Format: date */
            date: string;
            minimum_minor: string | null;
            maximum_minor: string | null;
            date_until: string;
            /** @enum {string} */
            event: "payment" | "expiry";
            /** @enum {string} */
            group: "scheduled" | "expected";
            included: boolean;
        };
        UpcomingCosts: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            minimum_minor: string;
            maximum_minor: string;
            unknown_count: number;
            items: components["schemas"]["UpcomingCost"][];
            scheduled: components["schemas"]["CostSubtotal"];
            expected: components["schemas"]["CostSubtotal"];
        };
        ReviewItem: {
            /** Format: uuid */
            entry_id: string;
            original: components["schemas"]["Entry"];
            draft: components["schemas"]["Entry"] | null;
            /** @enum {string} */
            status: "queued" | "processing" | "review" | "dismissed" | "completed" | "unchanged" | "stale" | "failed" | "auto_applied" | "undone";
            /** Format: date-time */
            created_at: string;
            reason: string;
            can_undo: boolean;
            question: string;
        };
        ReviewInbox: {
            items: components["schemas"]["ReviewItem"][];
            review_count: number;
            pending_count: number;
            failed_count: number;
            total: number;
            enabled: boolean;
            /** @description Empty when no further results remain. */
            next_cursor: string;
        };
        PaymentPlan: {
            /** @enum {string} */
            kind: "scheduled" | "expected" | "prepaid";
            excluded: boolean;
            remind: boolean;
            expires_on: string;
            date_until: string;
            interval_days: number;
            coverage_days: number;
            quantity: number;
            coverage_through: string;
            reminder_completed_on?: string;
        };
        CostSubtotal: {
            minimum_minor: string;
            maximum_minor: string;
            unknown_count: number;
        };
        ActivityPage: {
            items: components["schemas"]["Entry"][];
            total: number;
            next_cursor: string;
        };
        BrandIcon: {
            slug: string;
            title: string;
            /** @description Brand colour, six hex digits without # */
            hex: string;
            /** @description SVG path data in a 24×24 viewBox */
            path: string;
        };
        /** @description The assistant's reading of the task's notes. Server-owned; ignored on save. */
        FollowUp: {
            /** @description One-line readback of what happens next. */
            summary: string;
            /** @description When the assistant looks again. */
            check_on?: string;
            /** @enum {string} */
            status: "reading" | "ready" | "checking" | "waiting" | "failed";
            error?: string;
        };
        FollowUpEvent: {
            id: string;
            task_id: string;
            title: string;
            /** @enum {string} */
            action: "updated" | "replaced" | "finished" | "asked";
            message: string;
            question: string;
            answer: string;
            created_task?: string;
            /** @enum {string} */
            status: "new" | "seen" | "undone" | "answered";
            can_undo: boolean;
            /** Format: date-time */
            created_at: string;
        };
        FollowUpEvents: {
            items: components["schemas"]["FollowUpEvent"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
